### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by utkarshmttl** [getsanjeev/classifier-fundus-diabetic-retinopathy#1]
![input](https://user-images.githubusercontent.com/16596327/30451279-beedb542-99b0-11e7-8f46-a215dbb68695.jpg)

![input_ma](https://user-images.githubusercontent.com/16596327/30451295-cb73815c-99b0-11e7-8881-547576e85e11.jpg)
![input_maoverlay](https://user-images.githubusercontent.com/16596327/30451296-cb755dce-99b0-11e7-963a-3ceb0de184f7.jpg)

**Comment by utkarshmttl** [comment]
![retina](https://user-images.githubusercontent.com/16596327/30457494-28eefde8-99c5-11e7-96ce-19f713a9d989.jpg)

**Comment by utkarshmttl** [comment]
![headerim](https://user-images.githubusercontent.com/16596327/30458030-7398f9be-99c7-11e7-88f2-d39b4630a0a8.png)

**Comment by utkarshmttl** [comment]
![logo](https://user-images.githubusercontent.com/16596327/30467922-9d4985ce-9a05-11e7-81aa-9f5348eb40de.png)

**Comment by getsanjeev** [comment]
![20051019_38557_0100_pp_bloodvessel](https://user-images.githubusercontent.com/20872683/30469609-ae959b7a-9a0e-11e7-92b7-e2e90a49cc88.png)
